# Generated by Django 5.1.3 on 2024-11-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseo',
            fields=[
                ('id_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_insumo', models.CharField(max_length=255)),
                ('cantidad_insumo', models.IntegerField()),
                ('tipo_insumo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Computacion',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_material', models.CharField(max_length=255)),
                ('tipo_material', models.CharField(max_length=255)),
                ('cantidad_material', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesores',
            fields=[
                ('id_objeto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_objeto', models.CharField(max_length=255)),
                ('cantidad_objeto', models.IntegerField()),
                ('tipo_producto', models.CharField(max_length=255)),
            ],
        ),
    ]
