# Generated by Django 5.1.3 on 2024-12-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extraescolar',
            fields=[
                ('id_extraescolar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_extraescolar', models.CharField(max_length=255)),
                ('cantidad_extraescolar', models.IntegerField()),
                ('tipo_extraescolar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InteEscolar',
            fields=[
                ('id_inteescolar', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_inteescolar', models.CharField(max_length=255)),
                ('cantidad_inteescolar', models.IntegerField()),
                ('tipo_inteescolar', models.CharField(max_length=255)),
            ],
        ),
    ]
